/**
* タスク管理アプリAPI
* タスク管理アプリ用のAPI定義 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ValidationInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * 
 * @param code エラーコード
 * @param message エラーメッセージ
 * @param validationInfo バリデーション情報の配列
 */
@Parcelize
@JsonClass(generateAdapter = true)
data class Error (
    /* エラーコード */
    @Json(name = "code")
    val code: kotlin.Int,
    /* エラーメッセージ */
    @Json(name = "message")
    val message: kotlin.String,
    /* バリデーション情報の配列 */
    @Json(name = "validationInfo")
    val validationInfo: kotlin.collections.List<ValidationInfo>? = null
) : Parcelable

