/**
* タスク管理アプリAPI
* タスク管理アプリ用のAPI定義 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * タスク情報
 * @param id タスクID
 * @param name タスク名
 * @param isDone 完了したかどうか 
 * @param expiresIn 有効期限 ISO 8601形式 
 */
@Parcelize
@JsonClass(generateAdapter = true)
data class Task (
    /* タスクID */
    @Json(name = "id")
    val id: kotlin.String,
    /* タスク名 */
    @Json(name = "name")
    val name: kotlin.String,
    /* 完了したかどうか  */
    @Json(name = "isDone")
    val isDone: kotlin.Boolean,
    /* 有効期限 ISO 8601形式  */
    @Json(name = "expiresIn")
    val expiresIn: org.threeten.bp.OffsetDateTime
) : Parcelable

