/**
* タスク管理アプリAPI
* タスク管理アプリ用のAPI定義 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * タスク登録リクエストモデル
 * @param name タスク名
 * @param expiresIn 有効期限(yyyyMMdd)
 */
@Parcelize
@JsonClass(generateAdapter = true)
data class TaskPostAndPutParameter (
    /* タスク名 */
    @Json(name = "name")
    val name: kotlin.String,
    /* 有効期限(yyyyMMdd) */
    @Json(name = "expiresIn")
    val expiresIn: kotlin.String
) : Parcelable

