/**
* タスク管理アプリAPI
* タスク管理アプリ用のAPI定義 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * アクセストークン
 * @param tokenType トークンタイプ
 * @param accessToken アクセストークン
 * @param refreshToken リフレッシュトークン
 * @param expiresIn 有効秒数
 */
@Parcelize
@JsonClass(generateAdapter = true)
data class Token (
    /* トークンタイプ */
    @Json(name = "tokenType")
    val tokenType: kotlin.String,
    /* アクセストークン */
    @Json(name = "accessToken")
    val accessToken: kotlin.String,
    /* リフレッシュトークン */
    @Json(name = "refreshToken")
    val refreshToken: kotlin.String,
    /* 有効秒数 */
    @Json(name = "expiresIn")
    val expiresIn: kotlin.Long
) : Parcelable

