/**
* タスク管理アプリAPI
* タスク管理アプリ用のAPI定義 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * 
 * @param field 対象のフィールド名
 * @param rejectedValue 不正な入力値
 * @param message バリデーションメッセージ
 */
@Parcelize
@JsonClass(generateAdapter = true)
data class ValidationInfo (
    /* 対象のフィールド名 */
    @Json(name = "field")
    val field: kotlin.String,
    /* 不正な入力値 */
    @Json(name = "rejectedValue")
    val rejectedValue: kotlin.String,
    /* バリデーションメッセージ */
    @Json(name = "message")
    val message: kotlin.String
) : Parcelable

