name: code-gen

on:
  push:
    branches-ignore:
      - master
    paths:
      - "openapi.yaml"

env:
  DOCKER_BUILDKIT: 1

jobs:
  generate:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: taroshun32/openapi-generator
          path: openapi-generator
          ssh-key: ${{ secrets.DEPLOY_KEY_OPENAPI_GENERATOR }}

      - name: sync submodule
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: generate
        run: |
          sh ./.github/actions/code-gen/entrypoint.sh
          sh ./.github/actions/mock-json-gen/entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
